# 使用 3.8 版的設定檔，通常新版本會有新的功能，並支援新的設定參數
version: "3.8"

# 定義 service 的區塊，一個 service 設定可以用來啟動多個 container
services:
  todo-demo-api-service:
    container_name: todo-api-service
    image: passon/todo-demo-api
    ports:
      - 0.0.0.0:8220:8220
    environment:
      SOCKETCLUSTER_PORT: 8220
      AUTH_SECRET: test123
      SALT_SECRET: test456
      DB_USERNAME: postgres
      DB_DATABASE: todos_demo
      DB_PASSWORD: example
      DB_PORT: 5433
      DB_HOST: 139.162.91.214
      DB_DIALECT: postgres
      # SCC_STATE_SERVER_HOST: todo-scc-state
      # SCC_STATE_SERVER_PORT: 7777
