# 使用 3.8 版的設定檔，通常新版本會有新的功能，並支援新的設定參數
version: "3.8"

# 定義 service 的區塊，一個 service 設定可以用來啟動多個 container
services:
  # 定義一個叫 npm 的 service
  todo-scc-state:
    image: passon/scc-state
    container_name: todo-scc-state
    stdin_open: true
    tty: true
    working_dir: /usr/src/
    ports:
      - 0.0.0.0:7000:7777
    networks:
      todo-service-net:

  postgrelsqldb:
    container_name: postgrelsqldb
    image: postgres:15.7
    restart: always
    depends_on:
      - todo-scc-state
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 0.0.0.0:5433:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todos_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    networks:
      todo-service-net:

  todo-web-service:
    container_name: todo-web-service
    image: passon/todo-web
    depends_on:
      - postgrelsqldb
    networks:
      todo-service-net:
    ports:
      - 0.0.0.0:8320:80

  todo-demo-api-service:
    container_name: todo-api-service
    image: passon/todo-demo-api
    depends_on:
      - postgrelsqldb
    ports:
      - 0.0.0.0:8220:8220
    networks:
      todo-service-net:
    environment:
      SOCKETCLUSTER_PORT: 8220
      AUTH_SECRET: test123
      SALT_SECRET: test456
      DB_USERNAME: postgres
      DB_DATABASE: todos_demo
      DB_PASSWORD: example
      DB_PORT: 5432
      DB_HOST: postgrelsqldb
      DB_DIALECT: postgres
      SCC_STATE_SERVER_HOST: todo-scc-state
      SCC_STATE_SERVER_PORT: 7777

networks:
  todo-service-net:
    external: true
