# 使用 3.8 版的設定檔，通常新版本會有新的功能，並支援新的設定參數
version: "3.8"

# 定義 service 的區塊，一個 service 設定可以用來啟動多個 container
services:
  # 定義一個叫 npm 的 service
  todo-scc-state:
    image: passon/scc-state
    stdin_open: true
    tty: true
    working_dir: /usr/src/
    ports:
      - 0.0.0.0:7000:7777
    # volumes:
    #   - .:/usr/src/
    #   - /usr/src/node_modules
  postgrelsqldb:
    container_name: postgrelsqldb
    image: postgres:15.7
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 0.0.0.0:5433:5432
    environment:
      POSTGRES_DB: todos_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xup6jo3fup6
networks:
  todo-service-net:
    external: true