name: deploy-todo-web-production

on:
  pull_request:
    types: 
    - closed
    branches:
    - main
    paths:
    - 'deploy/todo-web/*'
    - 'packages/todo-web/**'
    - '.github/workflows/build-froentend-prod.yml'

jobs:
  do-deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0
      - name: Build And Deploy Todo Web
        run: |
          cd ./packages/todo-web/
          yarn install
          echo "${{ secrets.TODO_API_ENV }}" > ./.env
          yarn build
          scp -r ./build/** ${{ secrets.DEV_USER_NAME }}@${{ secrets.DEV_HOST }}:${{ secrets.TODO_WEB_TARGET }}