name: deploy-todo-web-production

on:
  pull_request:
    types: 
    - closed
    branches:
    - main
    paths:
    - 'deploy/todo-web/*'
    - 'packages/todo-web/**'
    - '.github/workflows/build-and-deploy-froentend-prod.yml'

jobs:
  do-deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.9.0
      - name: Build And Deploy Todo Web
        run: |
            echo "${{ secrets.TODO_WEB_ENV }}" > ./packages/todo-web/.env
            cd ./packages/todo-web/
            yarn install            
            yarn build
      - name: copy files to target server via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.WEB_HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_KEY_DEV_VALUE }}
          source: packages/todo-web/build/
          target: /var/www/html/todo-web.passon.tw/
          strip_components: 3
