name: deploy-todo-demo-web-production

on:
  pull_request:
    types: 
      - closed
    branches:
      - main
    paths:
      - 'apps/todo-demo-web/**'
      - '.github/workflows/deploy-todo-demo-web.yaml'

jobs:
  do-deployment:
    # if: github.event.pull_request.merged == true
    runs-on: mac-mini-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.17
      - name: Install Packages
        run: |
          pwd
          cd ./apps/todo-demo-web/
          yarn install
          echo "${{ secrets.TODO_WEB_ENV }}" > ./.env
          yarn build
          scp -r ./build/** root@${{ secrets.DEV_FROENT_HOST }}:/var/www/html/todo-demo-web.passon.tw
      